import { User, UserRole, DoctorSpecialty } from './types';

export const MOCK_USERS: User[] = [
    // Patient
    {
        id: 'user-pat-01',
        name: 'Alex Ray',
        role: UserRole.Patient,
        username: 'patient',
        password: 'password123',
        recordIds: ['pat-005', 'pat-004'],
    },
    // Nurse
    {
        id: 'user-nur-01',
        name: 'Jackie Smith',
        role: UserRole.Nurse,
        username: 'nurse',
        password: 'password123',
    },
    // Admin
    {
        id: 'user-adm-01',
        name: 'Admin User',
        role: UserRole.Admin,
        username: 'admin',
        password: 'password123',
    },
     // Pharmacy
    {
        id: 'user-pha-01',
        name: 'Maria Hill',
        role: UserRole.Pharmacy,
        username: 'pharmacy',
        password: 'password123',
    },
    // Engineering
    {
        id: 'user-eng-01',
        name: 'Tech Officer',
        role: UserRole.Engineering,
        username: 'engineer',
        password: 'password123',
    },
    // Lab Technician
    {
        id: 'user-lab-01',
        name: 'Leo Fitz',
        role: UserRole.LabTechnician,
        username: 'labtech',
        password: 'password123',
    },
    // Doctors
    {
        id: 'user-doc-01',
        name: 'Dr. Evelyn Reed',
        role: UserRole.Doctor,
        username: 'doctor-cardiologist',
        password: 'password123',
        specialty: DoctorSpecialty.Cardiologist,
        experienceYears: 15,
        profilePhotoUrl: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patientsTreated: 2500,
        patientsCured: 2350,
        patientsUndergoingTreatment: 75,
    },
    {
        id: 'user-doc-02',
        name: 'Dr. Ben Carter',
        role: UserRole.Doctor,
        username: 'doctor-dermatologist',
        password: 'password123',
        specialty: DoctorSpecialty.Dermatologist,
        experienceYears: 8,
        profilePhotoUrl: 'https://images.pexels.com/photos/5327656/pexels-photo-5327656.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patientsTreated: 1800,
        patientsCured: 1750,
        patientsUndergoingTreatment: 40,
    },
    {
        id: 'user-doc-03',
        name: 'Dr. Chloe Davis',
        role: UserRole.Doctor,
        username: 'doctor-neurologist',
        password: 'password123',
        specialty: DoctorSpecialty.Neurologist,
        experienceYears: 12,
        profilePhotoUrl: 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patientsTreated: 1500,
        patientsCured: 1300,
        patientsUndergoingTreatment: 110,
    },
    {
        id: 'user-doc-04',
        name: 'Dr. Sam Taylor',
        role: UserRole.Doctor,
        username: 'doctor-oncologist',
        password: 'password123',
        specialty: DoctorSpecialty.Oncologist,
        experienceYears: 18,
        profilePhotoUrl: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patientsTreated: 2000,
        patientsCured: 1200,
        patientsUndergoingTreatment: 300,
    },
    {
        id: 'user-doc-05',
        name: 'Dr. Maria Garcia',
        role: UserRole.Doctor,
        username: 'doctor-pediatrician',
        password: 'password123',
        specialty: DoctorSpecialty.Pediatrician,
        experienceYears: 10,
        profilePhotoUrl: 'https://images.pexels.com/photos/3786126/pexels-photo-3786126.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patientsTreated: 3500,
        patientsCured: 3400,
        patientsUndergoingTreatment: 80,
    },
    {
        id: 'user-doc-06',
        name: 'Dr. James Wilson',
        role: UserRole.Doctor,
        username: 'doctor-general',
        password: 'password123',
        specialty: DoctorSpecialty.General,
        experienceYears: 20,
        profilePhotoUrl: 'https://images.pexels.com/photos/4270088/pexels-photo-4270088.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patientsTreated: 5000,
        patientsCured: 4800,
        patientsUndergoingTreatment: 150,
    },
];
